### PR TITLE
_toolbar.backgroundColor changed to _toolbar.barTintColor to fix the …

### PR DESCRIPTION
**Pull request by fsalata**
Can you check if it fixes the issue #13 ?
Thank you.

### CODE REVIEW

**Comment by coffellas-cto** [comment]
This code actually breaks the disabled state of back/forward buttons: they look the same when enabled and disabled. See attached picture: one of them is enabled but you cannot say which one.

Also you have to consider whether bar is translucent or not. Toggle `translucent` property and check if it works under different circumstances.

screen shot 2016-10-05 at 20 07 37

**Comment by fsalata** [comment]
My bad, can you check if it's OK now?
The `translucent` property won't work because there is nothing behind the toolbar.

**Comment by fsalata** [comment]
Done.
Thank you.

**Comment by coffellas-cto** [comment]
issue  #13 Fixed

**Pull request merged**
